---
apiVersion: v1
kind: Namespace
metadata:
  name: bookstore
  labels:
    istio-injection: enabled
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: keycloak-lacave-tls
  namespace: bookstore
spec:
  secretName: keycloak-lacave-tls
  issuerRef:
    name: ca-lacave-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: Issuer
  commonName: keycloak.lacave
  organization:
  - Lacave CA
  dnsNames:
  - keycloak.lacave
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: keycloak
  namespace: bookstore
  labels:
    app: keycloak
spec:
  serviceName: keycloak
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: jboss/keycloak:latest
        env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/jboss/keycloak/standalone/data
      securityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-claim
  namespace: bookstore
  labels:
    app: keycloak
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: bookstore
  name: ingress-keycloak
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: ca-lacave-issuer
spec:
  tls:
  - hosts:
    - keycloak.lacave
    secretName: keycloak-lacave-tls
  rules:
  - host: keycloak.lacave
    http:
      paths:
      - path: /
        backend:
          serviceName: keycloak-service
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: bookstore
  labels:
    app: keycloak
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: keycloak
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: bookstoredb
  namespace: bookstore
  labels:
    app: bookstoredb
spec:
  serviceName: bookstoredb
  replicas: 1
  selector:
    matchLabels:
      app: bookstoredb
  template:
    metadata:
      labels:
        app: bookstoredb
    spec:
      containers:
      - name: bookstoredb
        # Ajuster le nom de l'image en fonction du repository Docker utilisé
        image: elfelip01/mongobookstore:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: bookstoredb-data
          mountPath: /mongo/data
      volumes:
        - name: bookstoredb-data
          persistentVolumeClaim:
            claimName: bookstoredb-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstoredb-claim
  namespace: bookstore
  labels:
    app: bookstoredb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: bookstoredb-service
  namespace: bookstore
  labels:
    app: bookstoredb
spec:
  ports:
  - name: client
    port: 27017
    protocol: TCP
  selector:
    app: bookstoredb
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bookstoreapi
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstoreapi
  template:
    metadata:
      labels:
        app: bookstoreapi
    spec:
      containers:
      - name: bookstoreapi
        # Ajuster le nom de l'image en fonction du repository Docker utilisé
        image: docker.lacave/booksapi:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
      # Spécifier le crédentiel si vous utilisé un repository Docker privé. 
      # Pas nécessaire pour Docker Hub
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: bookstoreapi-service
  namespace: bookstore
  labels:
    app: bookstoreapi
spec:
  ports:
  - name: client
    port: 80
    protocol: TCP
  selector:
    app: bookstoreapi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: bookstore
  name: ingress-bookstoreapi
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: bookstoreapi.lacave
    http:
      paths:
      - path: /
        backend:
          serviceName: bookstoreapi-service
          servicePort: 80