---
apiVersion: v1
kind: Namespace
metadata:
  name: bookstore
  labels:
    istio-injection: enabled
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: bookstoredb
  namespace: bookstore
  labels:
    app: bookstoredb
spec:
  serviceName: bookstoredb
  replicas: 1
  selector:
    matchLabels:
      app: bookstoredb
  template:
    metadata:
      labels:
        app: bookstoredb
    spec:
      containers:
      - name: bookstoredb
        image: elfelip01/mongobookstore:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: bookstoredb-data
          mountPath: /mongo/data

      volumes:
        - name: bookstoredb-data
          persistentVolumeClaim:
            claimName: bookstoredb-claim
            
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstoredb-claim
  namespace: bookstore
  labels:
    app: bookstoredb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: bookstoredb-service
  namespace: bookstore
  labels:
    app: bookstoredb
spec:
  ports:
  - name: client
    port: 27017
    protocol: TCP
  selector:
    app: bookstoredb
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: bookstoreapi
  namespace: bookstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstoreapi
  template:
    metadata:
      labels:
        app: bookstoreapi
    spec:
      containers:
      - name: bookstoreapi
        image: elfelip01/booksapi:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bookstoreapi-service
  namespace: bookstore
  labels:
    app: bookstoreapi
spec:
  ports:
  - name: client
    port: 80
    protocol: TCP
  selector:
    app: bookstoreapi
